export const ConfigKeys = {

    ConnectedServiceName: "ConnectedServiceName",
    Username: "username",
    Password: "password",
    TenantId: "tenantid",
    KeyVaultName: "keyvaultname",
    AuthCertName: "authcertname",
    SignCertName: "signcertname",
    ClientId: "ClientId",
    Intent: "Intent",
    ContentType: "ContentType",
    Audience: "Audience",
    MavenCheck: "MavenCheck",
    ContentOrigin: "ContentOrigin",
    ProductState: "ProductState",
    PackageLocation: "PackageLocation",
    Owners: "Owners",
    Approvers: "Approvers",
    MainPublisher: "MainPublisher",
    AppInsightsLoggingKey: "AppInsightsLoggingKey",
    ServiceEndpointUrl: "ServiceEndpointUrl",
    StatusPollingInterval: "StatusPollingInterval",
    Environment: "Environment",
    KvClientId: "KvClientId",
    KvTenantId: "KvTenantId",
    KvAuthCertName: "KvAuthCertName",
    KvSignCertName: "KvSignCertName",
    KvKeyVaultName: "KvKeyVaultName",
    KvSecret: "KvSecret",
    DomainTenantId: "DomainTenantId"
    
}